# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Snout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snout

   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'GoogleSignIn'
   pod 'Firebase/Database'

  target 'SnoutTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'Firebase/Database'

  end

  target 'SnoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end