# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PawTrails' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


    pod 'SwiftyJSON'
    pod 'Socket.IO-Client-Swift', '~> 11.1.3'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'YNDropDownMenu'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'RxSwift'

  # Pods for PawTrails

  target 'PawTrailsTests' do
    inherit! :search_paths  	
    use_frameworks!
  end

end
