# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'PawTrails' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '9.0'
  use_frameworks!

    pod 'Socket.IO-Client-Swift', '11.1.3'
    pod 'YNDropDownMenu'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'IQKeyboardManagerSwift', '5.0.0'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'SDWebImage'
    pod 'SCLAlertView'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'BarcodeScanner', '~> 2.1.2'
    pod 'MaterialComponents/Buttons'
    pod "Pulsator"


  target 'PawTrailsTests' do
    inherit! :search_paths  	
    use_frameworks!
  end

end
