# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PawTrails' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'FacebookCore'
	pod 'FacebookLogin'

  #pod 'Fabric'
  #pod 'TwitterKit'

  # Pods for PawTrails

  target 'PawTrailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
